#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TriCare.Droid.Resource", IsApplication=true)]

namespace TriCare.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::TriCare.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::TriCare.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_active_month_bg = global::TriCare.Droid.Resource.Color.calendar_active_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_bg = global::TriCare.Droid.Resource.Color.calendar_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_divider = global::TriCare.Droid.Resource.Color.calendar_divider;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_highlighted_day_bg = global::TriCare.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_inactive_month_bg = global::TriCare.Droid.Resource.Color.calendar_inactive_month_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_day_bg = global::TriCare.Droid.Resource.Color.calendar_selected_day_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_selected_range_bg = global::TriCare.Droid.Resource.Color.calendar_selected_range_bg;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_active = global::TriCare.Droid.Resource.Color.calendar_text_active;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_inactive = global::TriCare.Droid.Resource.Color.calendar_text_inactive;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selected = global::TriCare.Droid.Resource.Color.calendar_text_selected;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_selector = global::TriCare.Droid.Resource.Color.calendar_text_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Color.calendar_text_unselectable = global::TriCare.Droid.Resource.Color.calendar_text_unselectable;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::TriCare.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::TriCare.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_month_topmargin = global::TriCare.Droid.Resource.Dimension.calendar_month_topmargin;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_medium = global::TriCare.Droid.Resource.Dimension.calendar_text_medium;
			global::Xamarin.Forms.Labs.Droid.Resource.Dimension.calendar_text_small = global::TriCare.Droid.Resource.Dimension.calendar_text_small;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.ad16 = global::TriCare.Droid.Resource.Drawable.ad16;
			global::Xamarin.Forms.Labs.Droid.Resource.Drawable.calendar_bg_selector = global::TriCare.Droid.Resource.Drawable.calendar_bg_selector;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_grid = global::TriCare.Droid.Resource.Id.calendar_grid;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.calendar_view = global::TriCare.Droid.Resource.Id.calendar_view;
			global::Xamarin.Forms.Labs.Droid.Resource.Id.title = global::TriCare.Droid.Resource.Id.title;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.calendar_picker = global::TriCare.Droid.Resource.Layout.calendar_picker;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.dialog = global::TriCare.Droid.Resource.Layout.dialog;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.month = global::TriCare.Droid.Resource.Layout.month;
			global::Xamarin.Forms.Labs.Droid.Resource.Layout.week = global::TriCare.Droid.Resource.Layout.week;
			global::Xamarin.Forms.Labs.Droid.Resource.String.day_name_format = global::TriCare.Droid.Resource.String.day_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.full_date_format = global::TriCare.Droid.Resource.String.full_date_format;
			global::Xamarin.Forms.Labs.Droid.Resource.String.invalid_date = global::TriCare.Droid.Resource.String.invalid_date;
			global::Xamarin.Forms.Labs.Droid.Resource.String.library_name = global::TriCare.Droid.Resource.String.library_name;
			global::Xamarin.Forms.Labs.Droid.Resource.String.month_name_format = global::TriCare.Droid.Resource.String.month_name_format;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell = global::TriCare.Droid.Resource.Style.CalendarCell;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_CalendarDate = global::TriCare.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarCell_DayHeader = global::TriCare.Droid.Resource.Style.CalendarCell_DayHeader;
			global::Xamarin.Forms.Labs.Droid.Resource.Style.CalendarTitle = global::TriCare.Droid.Resource.Style.CalendarTitle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int calendar_text_selector = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int tricareselect_color = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_tcaretab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_tcaretab = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_tcaretab = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_tcaretab = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_tcaretab = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_tcaretab = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ad16 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int appMenu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_default_tcaretab = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_focused_tcaretab = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_cab_done_pressed_tcaretab = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_cab_done_tcaretab = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cab_background_bottom_tcaretab = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int cab_background_top_tcaretab = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int calendar_bg_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int list_focused_tcaretab = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int list_pressed_tcaretab = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int menu_dropdown_panel_tcaretab = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int patientIcon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int prescriberIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int prescriptionIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int progress_bg_tcaretab = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int progress_horizontal_tcaretab = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int progress_primary_tcaretab = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int progress_secondary_tcaretab = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int selectable_background_tcaretab = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int spinner_ab_default_tcaretab = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int spinner_ab_disabled_tcaretab = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int spinner_ab_focused_tcaretab = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int spinner_ab_pressed_tcaretab = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int spinner_background_ab_tcaretab = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int tab_indicator_ab_tcaretab = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tab_selected_focused_tcaretab = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tab_selected_pressed_tcaretab = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int tab_selected_tcaretab = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int tab_unselected_focused_tcaretab = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int tab_unselected_pressed_tcaretab = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int tab_unselected_tcaretab = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int tcareLoginLogo = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int tricareAndroid = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int tricareBG = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int tricareIcon = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int tricareIconA = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int tricareIos = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int tricareselect_activated_background_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int tricareselect_btn_default_disabled_focused_holo_light = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int tricareselect_btn_default_disabled_holo_light = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int tricareselect_btn_default_focused_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int tricareselect_btn_default_holo_light = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int tricareselect_btn_default_normal_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int tricareselect_btn_default_pressed_holo_light = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int tricareselect_btn_toggle_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tricareselect_btn_toggle_off_disabled_focused_holo_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int tricareselect_btn_toggle_off_disabled_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int tricareselect_btn_toggle_off_focused_holo_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int tricareselect_btn_toggle_off_normal_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int tricareselect_btn_toggle_off_pressed_holo_light = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int tricareselect_btn_toggle_on_disabled_focused_holo_light = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int tricareselect_btn_toggle_on_disabled_holo_light = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int tricareselect_btn_toggle_on_focused_holo_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int tricareselect_btn_toggle_on_normal_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int tricareselect_btn_toggle_on_pressed_holo_light = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int tricareselect_edit_text_holo_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int tricareselect_fastscroll_thumb_default_holo = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int tricareselect_fastscroll_thumb_holo = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int tricareselect_fastscroll_thumb_pressed_holo = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int tricareselect_item_background_holo_light = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int tricareselect_list_activated_holo = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int tricareselect_list_focused_holo = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int tricareselect_list_longpressed_holo = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int tricareselect_list_pressed_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int tricareselect_list_selector_background_transition_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int tricareselect_list_selector_disabled_holo_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int tricareselect_list_selector_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int tricareselect_text_select_handle_left = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int tricareselect_text_select_handle_middle = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int tricareselect_text_select_handle_right = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int tricareselect_textfield_activated_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int tricareselect_textfield_default_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int tricareselect_textfield_disabled_focused_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int tricareselect_textfield_disabled_holo_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int tricareselect_textfield_focused_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int tricareSplashA = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ViewCellBackground = 2130837588;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int btnCancel = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int btnSave = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int calendar_grid = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int rootView = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int signatureView = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int month = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SignaturePad = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SplashTheme = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int week = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int ApplicationName = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int Hello = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070005
			public const int ActionBar_Solid_Tcaretab = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int ActionBar_Transparent_Tcaretab = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int ActionBarTabStyle_Tcaretab = 2131165193;
			
			// aapt resource value: 0x7f07000c
			public const int ActionButton_CloseMode_Tcaretab = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int AutoCompleteTextViewTriCareSelect = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int ButtonTriCareSelect = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int DropDownListView_Tcaretab = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int DropDownNav_Tcaretab = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int EditTextTriCareSelect = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int ImageButtonTriCareSelect = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int ListViewTriCareSelect = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int ListViewTriCareSelect_White = 2131165204;
			
			// aapt resource value: 0x7f070007
			public const int PopupMenu_Tcaretab = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int ProgressBar_Tcaretab = 2131165195;
			
			// aapt resource value: 0x7f070015
			public const int SpinnerItemTriCareSelect = 2131165205;
			
			// aapt resource value: 0x7f070004
			public const int Theme_Tcaretab = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int Theme_Tcaretab_Widget = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int ToggleTriCareSelect = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int TriCareSelect = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int _TriCareSelect = 2131165207;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
